### ISSUE TITLE
No module named 'waymo_extractor

### ISSUE THREAD

**Issue by z393** [DapengFeng/waymo-toolkit#1]
Traceback (most recent call last):
  File "tools/extract.py", line 7, in <module>
    from waymo_toolkit.extractor import ImageExtractor, LabelExtractor, LaserExtractor
  File "/home/hy/anaconda3/envs/waymo-toolkit/lib/python3.7/site-packages/waymo_toolkit-0.1.0-py3.7.egg/waymo_toolkit/extractor/__init__.py", line 1, in <module>
  File "/home/hy/anaconda3/envs/waymo-toolkit/lib/python3.7/site-packages/waymo_toolkit-0.1.0-py3.7.egg/waymo_toolkit/extractor/image.py", line 7, in <module>
ModuleNotFoundError: No module named 'waymo_extractor'
I met this error, how to fix it?

**Comment by DapengFeng** [comment]
@z393 Hi, thanks for your comment, and I upload the revised version to the master repo.
